### PR TITLE
Add flag for case having had an abatement notice.

### PR DESCRIPTION
**Pull request by dracos**
`case.had_abatement_notice` returns true if it has had such an action on it in the past (as with timeline, looking at actions on this case, plus any actions on merged-in cases after the point they were merged).

### CODE REVIEW

**Review by zarino — APPROVED** [review]
Code looks good! I‘ve added a commit that uses the `case.had_abatement_notice` property to display a tag in the UI whenever a case is displayed:

Screenshot 2021-12-16 at 12 00 45

Screenshot 2021-12-16 at 12 01 02

As part of this (primarily to cut down on text clutter when assistive device users cycle through links, but also to avoid unwanted underlines which are hard to reset in CSS) I’ve moved the case ID tag (and this new abatement tag) out of the `<a>` in case list item titles. Do you think that’ll be an issue?

**Comment by dracos** [comment]
"Do you think that’ll be an issue?" nah, I doubt anyone has got used to clicking on the IDs yet who will complain ;)

**Comment by dracos** [comment]
Not sure how you broke the tests, will look :)

**Comment by zarino** [comment]
> Not sure how you broke the tests

Nor am I! Thanks for investigating.

**Pull request merged**
